module.exports = [
  {
    name: "John Stevenson",
    age: 28,
    accountActive: false,
    balance: 3218.19,
    payments: [],
  },
  {
    name: "French Richards",
    age: 27,
    accountActive: true,
    balance: 3852.25,
    payments: [],
  },
  {
    name: "Maddox Leon",
    age: 32,
    accountActive: false,
    balance: 3740.04,
    payments: [],
  },
  {
    name: "Chris Dixon",
    age: 24,
    accountActive: true,
    balance: 3757.91,
    payments: [],
  },
  {
    name: "Tucker Adams",
    age: 28,
    accountActive: true,
    balance: 2435.85,
    payments: [],
  },
  {
    name: "Morales Zamora",
    age: 20,
    accountActive: false,
    balance: 2356.17,
    payments: [],
  },
  {
    name: "Wolf Estes",
    age: 39,
    accountActive: false,
    balance: 2389.4,
    payments: [],
  },
  {
    name: "Janine Kelley",
    age: 23,
    accountActive: true,
    balance: 1044.73,
    payments: [],
  },
  {
    name: "Waters Whitehead",
    age: 28,
    accountActive: false,
    balance: 3317.56,
    payments: [],
  },
  {
    name: "Foster Mcfarland",
    age: 33,
    accountActive: false,
    balance: 2548.77,
    payments: [],
  },
  {
    name: "Burke Juarez",
    age: 37,
    accountActive: true,
    balance: 2385.3,
    payments: [],
  },
  {
    name: "Clare Cantrell",
    age: 22,
    accountActive: true,
    balance: 1291.55,
    payments: [],
  },
  {
    name: "Leila Mosley",
    age: 27,
    accountActive: false,
    balance: 2657.08,
    payments: [],
  },
  {
    name: "Duran Serrano",
    age: 38,
    accountActive: false,
    balance: 2817.92,
    payments: [],
  },
  {
    name: "Leticia Molina",
    age: 26,
    accountActive: true,
    balance: 2581.05,
    payments: [],
  },
  {
    name: "Ward Frye",
    age: 26,
    accountActive: false,
    balance: 3397.81,
    payments: [],
  },
  {
    name: "Hoover Goodman",
    age: 38,
    accountActive: true,
    balance: 2234.56,
    payments: [],
  },
  {
    name: "Mueller Meadows",
    age: 33,
    accountActive: true,
    balance: 2716.41,
    payments: [],
  },
  {
    name: "Flynn Middleton",
    age: 24,
    accountActive: false,
    balance: 2023.01,
    payments: [],
  },
  {
    name: "Carol Whitney",
    age: 22,
    accountActive: true,
    balance: 1385.98,
    payments: [],
  },
  {
    name: "Terry Mcmahon",
    age: 36,
    accountActive: false,
    balance: 2082.97,
    payments: [],
  },
  {
    name: "Holly Riddle",
    age: 27,
    accountActive: true,
    balance: 2842.51,
    payments: [],
  },
  {
    name: "Maxwell Mckay",
    age: 24,
    accountActive: true,
    balance: 2366.35,
    payments: [],
  },
  {
    name: "Ferrell Myers",
    age: 20,
    accountActive: true,
    balance: 2693.51,
    payments: [],
  },
  {
    name: "Gilda Grimes",
    age: 22,
    accountActive: true,
    balance: 2234.65,
    payments: [],
  },
  {
    name: "Juana Whitley",
    age: 35,
    accountActive: false,
    balance: 1555.12,
    payments: [],
  },
  {
    name: "Geraldine Wiley",
    age: 20,
    accountActive: false,
    balance: 1643.22,
    payments: [],
  },
  {
    name: "Nellie Craig",
    age: 33,
    accountActive: false,
    balance: 3882.72,
    payments: [],
  },
  {
    name: "Snider Sykes",
    age: 28,
    accountActive: true,
    balance: 3562.46,
    payments: [],
  },
  {
    name: "Marla Lamb",
    age: 31,
    accountActive: false,
    balance: 2176.87,
    payments: [],
  },
  {
    name: "Barnes Fitzpatrick",
    age: 24,
    accountActive: true,
    balance: 3779.92,
    payments: [],
  },
  {
    name: "Bolton Mcguire",
    age: 40,
    accountActive: true,
    balance: 1840.25,
    payments: [],
  },
  {
    name: "Candace French",
    age: 26,
    accountActive: false,
    balance: 2340.05,
    payments: [],
  },
  {
    name: "Alexis Whitfield",
    age: 29,
    accountActive: false,
    balance: 2404.32,
    payments: [],
  },
  {
    name: "House Wilson",
    age: 38,
    accountActive: true,
    balance: 1411.98,
    payments: [],
  },
  {
    name: "Melba Clayton",
    age: 38,
    accountActive: false,
    balance: 2202.82,
    payments: [],
  },
  {
    name: "Wright Olson",
    age: 24,
    accountActive: false,
    balance: 3527.51,
    payments: [],
  },
  {
    name: "Hays Faulkner",
    age: 39,
    accountActive: false,
    balance: 3509.28,
    payments: [],
  },
  {
    name: "Watts Daniels",
    age: 36,
    accountActive: true,
    balance: 2385.18,
    payments: [],
  },
];
